### ISSUE TITLE
Private Endpoint for file storage is required

### ISSUE THREAD

**Issue by jhirono** [ezwiefel/azure-machine-learning-bicep#5]
Workspace storage requires a private endpoint for file on top of blob. The current one creates a private endpoint for blob only.

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-secure-workspace-vnet#secure-azure-storage-accounts-with-private-endpoints

**Comment by ezwiefel** [comment]
@jhirono - SUPER late (I didn't see the issue in GH until recently), but the Bicep has been updated.
